//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_InMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODZCase
    {
        public int ODZCaseId { get; set; }
        public Nullable<long> ICI { get; set; }
        public Nullable<int> ODZID { get; set; }
        public Nullable<int> ODZTeamId { get; set; }
        public Nullable<int> BDZId { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public Nullable<int> IncidentTypeId { get; set; }
    }
}
